### ISSUE TITLE
randomaccess issue [webtorrent]

### ISSUE THREAD

**Issue by ThaUnknown** [mathiasvr/matroska-subtitles#5]
I'm trying to parse subtitles on random video fragments using the code in [random-access.js](https://github.com/mathiasvr/matroska-subtitles/blob/master/examples/random-access.js) but I keep running into issues:
```js
bundle.js:4663 Uncaught Error: write after end
    at writeAfterEnd (bundle.js:4663)
    at MatroskaSubtitles.Writable.write (bundle.js:4707)
    at FileStream.ondata (webtorrent.min.js:6)
    at emitOne (webtorrent.min.js:6)
    at FileStream.EventEmitter.emit (webtorrent.min.js:6)
    at addChunk (webtorrent.min.js:6)
    at readableAddChunk (webtorrent.min.js:6)
    at FileStream.Readable.push (webtorrent.min.js:6)
    at webtorrent.min.js:1
    at webtorrent.min.js:6
```
it finds the tracks in the first piece, but then gives that error on the following ones, my code:
```js
var parser = new MatroskaSubtitles()

parser.once('tracks', function (tracks) {
  console.log(tracks)
  parser = new MatroskaSubtitles(parser)

  parser.on('subtitle', function (subtitle, trackNumber) {
    console.log('track ' + trackNumber + ':', subtitle)
  })
})
```
and the filestreams are video requests from a http server
```js
file.createReadStream(range).pipe(parser)
```
the general idea of this is to try to parse subtitles of videos fragments as they come into the client from the HTTP server, I tried doing it on the entire file at once, without specifying ranges and it worked, but on specific fragments, it errors out, is it because I specify ends of filestreams?

**Comment by mathiasvr** [comment]
The random access feature is quite low level and experimental. I originally included it to support video seeking but was never able to make it work well. I'm not sure about your exact problem, but I seem to remember that you have to supply an offset that fits with the position of an mkv track, such that it does not begin parsing halfway through a track.
I honestly can't remember though. What exactly is the `range` you pass in?

**Comment by ThaUnknown** [comment]
> The random access feature is quite low level and experimental. I originally included it to support video seeking but was never able to make it work well. I'm not sure about your exact problem, but I seem to remember that you have to supply an offset that fits with the position of an mkv track, such that it does not begin parsing halfway through a track.
> I honestly can't remember though. What exactly is the `range` you pass in?

thanks for the reply, well video seeking is what I tried doing, the range I pass in is what the HTML player requests from the "Http server" in which case it's just a [service worker](https://github.com/jimmywarting/webtorrent-server-browser), and to be more specific I create a copy of [this](https://github.com/jimmywarting/webtorrent-server-browser/blob/master/index.html#L64) filestream

**Comment by ThaUnknown** [comment]
> but I seem to remember that you have to supply an offset that fits with the position of an mkv track, such that it does not begin parsing halfway through a track.

well I guess I'll try to read up on this and try it, tho it's gonna be a kinda botched solution

**Comment by mathiasvr** [comment]
I will try to take a look as well when I have time. If I understand correctly the browser handles playback/seeking/etc. which should mean the ranges are already properly aligned.

**Comment by ThaUnknown** [comment]
> I will try to take a look as well when I have time. If I understand correctly the browser handles playback/seeking/etc. which should mean the ranges are already properly aligned.

yes, the browser handles pretty much everything, I haven't experimented with it a lot after this, it's possible that I made some mistake, but please if you find the time try looking into it <3

**Comment by mathiasvr** [comment]
I played a bit around with the service worker project and found there was definitely a problem on my part.
I have released a new patch as v2.0.4 which hopefully solves your issue as well.

That being said this module doesn't currently handle these tasks well since it's not reading the data in sync with the player.
I originally made it as a transform stream but that caused other problems.  Now 4 years down the line I don't quite remember what, but I might take another look at it since I always wanted a nicer solution 😅

**Comment by ThaUnknown** [comment]
> I played a bit around with the service worker project and found there was definitely a problem on my part.
> I have released a new patch as v2.0.4 which hopefully solves your issue as well.
> 
> That being said this module doesn't currently handle these tasks well since it's not reading the data in sync with the player.
> I originally made it as a transform stream but that caused other problems. Now 4 years down the line I don't quite remember what, but I might take another look at it since I always wanted a nicer solution 😅

I'm still getting the same error, gonna assume its an issue on my end then, I'm guessing webtorrent's filestream is incompatible with your code, which is weird considering they use the same filestream lib

**Comment by mathiasvr** [comment]
I looked into it a bit more and found that the ranges chrome requests are not aligned to the mkv clusters as I thought.
Not sure how these ranges are chosen, but the EBML parser used by this module doesn't like it 😞
I think we can make it work by using mkv cue data to properly align the data before parsing.
I have become quite interested in the mkv format again, so will see what I can do 😃 

But anyway currently random access is unfortunately not really going to work.

**Comment by ThaUnknown** [comment]
> I looked into it a bit more and found that the ranges chrome requests are not aligned to the mkv clusters as I thought.
> Not sure how these ranges are chosen, but the EBML parser used by this module doesn't like it 😞
> I think we can make it work by using mkv cue data to properly align the data before parsing.
> I have become quite interested in the mkv format again, so will see what I can do 😃
> 
> But anyway currently random access is unfortunately not really going to work.

welp, spent the past 2 days trying shit, and pretty much can confirm that it doesn't work, the code I showed above was wrong, very wrong, and I'm yet to get it working correctly, also the ranges specified don't have an end, so what ends up happening is the parser gets a proper request from the start but the end of the file stream is the end of the file itself, I have no idea how one would implement what you have currently into a proper player with seeking, if you have any ideas for code, please show them, what I currently have is:
```
var parser
function parseSubs(stream) {
  console.log("running")
  if (parser) {
    var fragParser = new MatroskaSubtitles(parser)
  } else {
    var fragParser = new MatroskaSubtitles()
  }
  fragParser.once('tracks', function (pTracks) {
    parser = new MatroskaSubtitles(fragParser)
    parseSubs(stream)
    console.log(pTracks)
  })
  fragParser.on('subtitle', function (subtitle, trackNumber) {
    console.log(subtitle)
  })
  stream.pipe(fragParser)
}
```
but it doesn't work anyways

**Comment by ThaUnknown** [comment]
I don't think seeking is even possible with the current implementation, even if it was aligned with the tracks, from what I tested creating a new parser that copies metadata from an old parser destroys the old one, that why in the code above inside .once tracks I had a recursive parseSubs, not that it helped tho so the metadata would need to be passed in some different way completely

**Comment by ThaUnknown** [comment]
and you can't continue to pass the parser data between requests because the requests don't have an end range specified and seeking often makes multiple piece requests

**Comment by mathiasvr** [comment]
I agree the current implementation is very inappropriate for this task.

I've been hacking away at it and have something that kinda works, sometimes. 😅 
I have made the module into a passthrough stream that intercepts the mkv data as it is streamed to the player, and records cueing data to allow it to properly parse the ranges.

The biggest problem with testing right now is that chrome seems to force media caching, and it will of course only work when media is actually being downloaded through the service worker. Also sometimes it seems like a new range is being requested before the subtitles are parsed, but that shouldn't be possible since playback isn't affected? Maybe caching problem again, I have to investigate further. 

All is of course very early experimental work, but I have a sample of it at https://github.com/mathiasvr/webtorrent-server-browser if you want to test it. It works best if the cue data is at the beginning of the file because it can avoid even more caching annoyance.

**Comment by ThaUnknown** [comment]
> I agree the current implementation is very inappropriate for this task.
> 
> I've been hacking away at it and have something that kinda works, sometimes. 😅
> I have made the module into a passthrough stream that intercepts the mkv data as it is streamed to the player, and records cueing data to allow it to properly parse the ranges.
> 
> The biggest problem with testing right now is that chrome seems to force media caching, and it will of course only work when media is actually being downloaded through the service worker. Also sometimes it seems like a new range is being requested before the subtitles are parsed, but that shouldn't be possible since playback isn't affected? Maybe caching problem again, I have to investigate further.
> 
> All is of course very early experimental work, but I have a sample of it at https://github.com/mathiasvr/webtorrent-server-browser if you want to test it. It works best if the cue data is at the beginning of the file because it can avoid even more caching annoyance.

not sure if I did something wrong but I ran into this issue:
```js
bundle.js:13089 Uncaught TypeError: ebml.Decoder is not a constructor
    at new MatroskaSubtitles (bundle.js:13089)
```
https://github.com/mathiasvr/matroska-subtitles/blob/cues/index.js#L21

**Comment by mathiasvr** [comment]
Yes I had this problem too, did you build with `npm run build`? Seems to be a problem with the ebml package.

**Comment by ThaUnknown** [comment]
> Yes I had this problem too, did you build with `npm run build`? Seems to be a problem with the ebml package.

I used browserify, so I think install not build, what should I have done?
I ran npm install --save mathiasvr/matroska-subtitles#cues

**Comment by mathiasvr** [comment]
Ah okay, I made a `build` script that runs `webpack --mode=development --resolve-alias ebml=ebml/lib/ebml.esm.js`.
So using webpack instead and fixing the ebml resolution error.
You can use it by running:
```
npm install
npm run build
```
directly in the directory of my fork of webtorrent-server-browser to try the example.

If you want to use `mathiasvr/matroska-subtitles#cues` in your own project with browserify you will have to figure out how to use module resolution alias, or simply delete the `browser` attribute from the ebml package.json (to work around the bug).
But yeah it's pretty messy 😓 I will see if I can fix all these workarounds.

**Comment by mathiasvr** [comment]
I updated the `matroska-subtitles#cues` branch and my `webtorrent-server-browser` example.
Should be easier to build? 🤷‍♂️ 
Also fixed a cue sorting issue and some stuff so now it works much smoother. I can keep seeking around and see the subtitles parsed almost instantly.
I may have reduced the caching problem but I still have some trouble with it.

**Comment by ThaUnknown** [comment]
> I updated the `matroska-subtitles#cues` branch and my `webtorrent-server-browser` example.
> Should be easier to build? 🤷‍♂️
> Also fixed a cue sorting issue and some stuff so now it works much smoother. I can keep seeking around and see the subtitles parsed almost instantly.
> I may have reduced the caching problem but I still have some trouble with it.

actually outstanding, thanks so much, I've wasted so much time trying to get this to work xD
on the surface it seems to be working properly, I'll do some further testing if I don't find any issues I'll close this issue

**Comment by ThaUnknown** [comment]
seems like the first stream that's created never parses the cues? meaning that until you seek at least once it won't parse subtitles, kinda a problem for autoplay [I use autoplay because on chrome it increases the video buffer from 25 to 53 seconds IIRC since the preload attribute is useless nowdays], but even without autoplay it could be an issue, not too sure what it's related to tho,
guessing this is related to "No cues for offset **filesize**. Subtitle parsing disabled." This happens when loading video metadata before any content is actually loaded I think

also, by caching issues, do you mean when seeking or when reloading the video?

**Comment by mathiasvr** [comment]
I've spent lots of time on it myself and even gave up 😆 Your issue inspired me to try this approach 👍 

Yes, I'm having some issues when reloading videos, such that the initial part of the video (specifically the part with all the track information that's needed for finding subtitles) is not being requested by the service worker :(
Actually I think we can just force offset 0 for the first instance and then handle the range request after the tracks event, but then we kinda also have to force the cue offset. It's a bit problematic since the subtitle parser is not in charge of the stream, so I'm really hoping to avoid it and just let the browser/player handle it.

I haven't tried autoplay, does it even work in chrome anymore?
Do you think your problem could be similar to mine? Like the first part not being requested or do you get a range request for offset 0?

> guessing this is related to "No cues for offset **filesize**. Subtitle parsing disabled."

Do you get a range request for the total filesize of the file? I don't think I've seen that, but I'm not sure it's a problem as long as a new range request is made later? 

Probably more testing is needed.

Currently, important things for seeking to work are: First the parser must process the mkv header from offset 0, and must then parse the cue segment.
Normally (what I'm currently seeing), for an uncached video, the browser makes a range request for offset 0 and then immediately a range request for the cue segment offset (unless it was already located at the beginning of the file). This happens to be perfect for the parser.
We basically have to figure out the cases when this doesn't happen.

**Comment by mathiasvr** [comment]
Also, I'm having a lot of trouble making webtorrent load my test files. I'm seeding them with webtorrent desktop, not sure if this is related.

**Comment by ThaUnknown** [comment]
> Also, I'm having a lot of trouble making webtorrent load my test files. I'm seeding them with webtorrent desktop, not sure if this is related.

IIRC this happens when you re-load the website a lot, maybe some connection throttle? not sure but I've had this issue for ages and I'm yet to figure it out why it happens, usually restarting the browser fixes it, for test files I use top-seeded stuff from sites like pbay and a few others

**Comment by ThaUnknown** [comment]
> Yes, I'm having some issues when reloading videos, such that the initial part of the video (specifically the part with all the track information that's needed for finding subtitles) is not being requested by the service worker :(
yeah, the metadata seems to be cached, I don't think it would be a major problem on a finished website since you could just "block"/discourage refreshing
I haven't tried autoplay, does it even work in chrome anymore?
Do you think your problem could be similar to mine? Like the first part not being requested or do you get a range request for offset 0?

>> guessing this is related to "No cues for offset filesize. Subtitle parsing disabled."

> Do you get a range request for the total filesize of the file? I don't think I've seen that, but I'm not sure it's a problem as long as a new range request is made later?

this is what happens on autoplay: 
![image](https://user-images.githubusercontent.com/6506529/93144038-6f19dc00-f6e9-11ea-8100-411b8c59e213.png)
I'm fairly sure it's because it requests the next video piece before the first one [with the cue data maybe? not too sure how mkv works] downloads, meaning it can't be parsed in time? that's my guess, so it requests the next piece killing the previous parser instance?

**Comment by ThaUnknown** [comment]
![image](https://user-images.githubusercontent.com/6506529/93144392-30d0ec80-f6ea-11ea-8a8a-b6f3269d045f.png)
and this is what happens without autoplay, letting the video sit there without playing it

**Comment by mathiasvr** [comment]
> IIRC this happens when you re-load the website a lot, maybe some connection throttle? not sure but I've had this issue for ages and I'm yet to figure it out why it happens, usually restarting the browser fixes it, for test files I use top-seeded stuff from sites like pbay and a few others

Well great, cause it's not like I'm reloading every second! 🤣 
I have actually only tested with small'ish files because I needed to track down bugs. I think it's stable enough now to try some larger things 👍

**Comment by ThaUnknown** [comment]
weird thing is, even with caching disabled via devtools metadata still seems to be cached 🤔 what the actual fuck

**Comment by ThaUnknown** [comment]
setting the video to only load metadata initially causes this:
![image](https://user-images.githubusercontent.com/6506529/93144680-d8e6b580-f6ea-11ea-9e7c-6cd052939895.png)
ignore the tracker errors

**Comment by ThaUnknown** [comment]
damn, the preload and autoplay properties cause all sorts of issues....

**Comment by ThaUnknown** [comment]
so seems like trying to parse metadata disables subtitle parsing ~~for that filestream instance~~[this is wrong I think], that's what causing my issues, this is caching issues aside which are in some way related to the service worker, the issue is emptying cache and hard reloading causes the service worker to unregister and the first file load causes a 404 because the port listener isn't initiated?

**Comment by mathiasvr** [comment]
> this is what happens on autoplay:
> ![image](https://user-images.githubusercontent.com/6506529/93144038-6f19dc00-f6e9-11ea-8100-411b8c59e213.png)
> I'm fairly sure it's because it requests the next video piece before the first one [with the cue data maybe? not too sure how mkv works] downloads, meaning it can't be parsed in time? that's my guess, so it requests the next piece killing the previous parser instance?

This is definitely something that should be looked into, the weird thing is just that since the parser is now a passthrough stream, killing an instance should cause playback issues as well? In other words, when the data stream reaches the player from webtorrent, it has already been parsed.

**Comment by mathiasvr** [comment]
> so seems like trying to parse metadata disables subtitle parsing ~for that filestream instance~[this is wrong I think], that's what causing my issues, this is caching issues aside which are in some way related to the service worker, the issue is emptying cache and hard reloading causes the service worker to unregister and the first file load causes a 404 because the port listener isn't initiated?

Thanks for testing, I'll try looking into it. The disabling subtitle parsing thing only applies to a single instance, but it could potentially make it really hard to ever get the cue list.
I've seen the 404 things, wasn't aware why it happened - good to know.

**Comment by ThaUnknown** [comment]
> > this is what happens on autoplay:
> > ![image](https://user-images.githubusercontent.com/6506529/93144038-6f19dc00-f6e9-11ea-8100-411b8c59e213.png)
> > I'm fairly sure it's because it requests the next video piece before the first one [with the cue data maybe? not too sure how mkv works] downloads, meaning it can't be parsed in time? that's my guess, so it requests the next piece killing the previous parser instance?
> 
> This is definitely something that should be looked into, the weird thing is just that since the parser is now a passthrough stream, killing an instance should cause playback issues as well? In other words, when the data stream reaches the player from webtorrent, it has already been parsed.

[this is my understanding, it might be VERY wrong since I don't know much on this] I don't think so? from what I tested creating a new filestream doesn't kill the previous instances, so the player can async request pieces and it doesn't really care what order it receives them in or when it receives them, but this also would mean that the filestreams never get closed which I don't think is the case, maybe only kill previous parser instances after the stream itself has been killed/destroyed?

**Comment by ThaUnknown** [comment]
also the subtitles should be probably parsed async because it might lag video playback in areas which might already have parsed/processed subtitles

**Comment by mathiasvr** [comment]
Just updated the branch. When the first instance was not at offset 0, everything was going bug crazy. I think it should probably not be allowed, but will make testing easier - I hope.

**Comment by mathiasvr** [comment]
> [this is my understanding, it might be VERY wrong since I don't know much on this] I don't think so? from what I tested creating a new filestream doesn't kill the previous instances, so the player can async request pieces and it doesn't really care what order it receives them in or when it receives them, but this also would mean that the filestreams never get closed which I don't think is the case, maybe only kill previous parser instances after the stream itself has been killed/destroyed?

I'm also not too sure because I have kinda just let webtorrent handle the streams. Not sure how they get closed or not, I just hoped we didn't have to look into it. 😅

This is becoming so over-engineered for something that could easily be done in chromium... Oh well, I guess since they don't support built-in subs yet they'll probably never get it done.

**Comment by ThaUnknown** [comment]
> Just updated the branch. When the first instance was not at offset 0, everything was going bug crazy. I think it should probably not be allowed, but will make testing easier - I hope.

seems like most of my issues were caused by either preload or autoplay, they do some REALLY weird shit where some fragments of the video and metadata aren't requested at all, that's what was causing my initial cue issues, not using those breaks some of my other modules, but I'm okay with parting ways with them for this to work

**Comment by ThaUnknown** [comment]
> > [this is my understanding, it might be VERY wrong since I don't know much on this] I don't think so? from what I tested creating a new filestream doesn't kill the previous instances, so the player can async request pieces and it doesn't really care what order it receives them in or when it receives them, but this also would mean that the filestreams never get closed which I don't think is the case, maybe only kill previous parser instances after the stream itself has been killed/destroyed?
> 
> I'm also not too sure because I have kinda just let webtorrent handle the streams. Not sure how they get closed or not, I just hoped we didn't have to look into it. 😅
> 
> This is becoming so over-engineered for something that could easily be done in chromium... Oh well, I guess since they don't support built-in subs yet they'll probably never get it done.

I parse the subtitles, add them to a vtt cue which I then append to a vtt track, and trust me when I say: looking at the VTT API alone I'm surprised they even support subtitles at all, shit's done so fucking garbage its crazy, 1/2 the features don't work or are dropped, getting as much as [.ass](http://www.cccp-project.net/stuff/ass-specs.pdf) positions converted to VTT positions took me all day and it's still mostly patchworked like offsets with blank lines and such

**Comment by ThaUnknown** [comment]
> > Just updated the branch. When the first instance was not at offset 0, everything was going bug crazy. I think it should probably not be allowed, but will make testing easier - I hope.
> 
> seems like most of my issues were caused by either preload or autoplay, they do some REALLY weird shit where some fragments of the video and metadata aren't requested at all, that's what was causing my initial cue issues, not using those breaks some of my other modules, but I'm okay with parting ways with them for this to work

that said, even launching the video playback early manually breaks the initial parsing :&, this is without caching etc, so it's 100% not a caching issue

**Comment by mathiasvr** [comment]
> that said, even launching the video playback early manually breaks the initial parsing :&, this is without caching etc, so it's 100% not a caching issue

It's just so weird with how the stream is processed, caching seems like the only way it could sidestep the parser.
But I have no idea, at least there's hope it could be fixed, I'll keep debugging.

**Comment by ThaUnknown** [comment]
> > that said, even launching the video playback early manually breaks the initial parsing :&, this is without caching etc, so it's 100% not a caching issue
> 
> It's just so weird with how the stream is processed, caching seems like the only way it could sidestep the parser.
> But I have no idea, at least there's hope it could be fixed, I'll keep debugging.

I could just patch it over by preventing playback on .mkv files until it finds cues, but since I don't know how that's handled it could cause issues when there are none and it's not the best solution for other people that'd like to use the lib

**Comment by mathiasvr** [comment]
> I parse the subtitles, add them to a vtt cue which I then append to a vtt track, and trust me when I say: looking at the VTT API alone I'm surprised they even support subtitles at all, shit's done so fucking garbage its crazy, 1/2 the features don't work or are dropped, getting as much as [.ass](http://www.cccp-project.net/stuff/ass-specs.pdf) positions converted to VTT positions took me all day and it's still mostly patchworked like offsets with blank lines and such

Sounds very cool, I didn't know you had that much done! Can you add the subtitles dynamically as they are parsed?
I hadn't even thought .ass positioning would be possible, impressive.

**Comment by ThaUnknown** [comment]
> > I parse the subtitles, add them to a vtt cue which I then append to a vtt track, and trust me when I say: looking at the VTT API alone I'm surprised they even support subtitles at all, shit's done so fucking garbage its crazy, 1/2 the features don't work or are dropped, getting as much as [.ass](http://www.cccp-project.net/stuff/ass-specs.pdf) positions converted to VTT positions took me all day and it's still mostly patchworked like offsets with blank lines and such
> 
> Sounds very cool, I didn't know you had that much done! Can you add the subtitles dynamically as they are parsed?
> I hadn't even thought .ass positioning would be possible, impressive.

![unknown](https://cdn.discordapp.com/attachments/746388251933278250/753335323915714771/unknown.png)
yup. at least most of it, that includes linebreaks etc etc, vtt lacks a LOT of shit, so for example for a 2px outline around the text I needed to create 8 text shadows, but it actually works pretty well and I was really stubborn on using vtt cues for compatibility reasons with other platforms and devices over a custom display

regions don't work, and aren't supported in some browsers ex: chrome, but are in firefox, its a shitstorm 😓

**Comment by mathiasvr** [comment]
> yup. at least most of it, that includes linebreaks etc etc, vtt lacks a LOT of shit, so for example for a 2px outline around the text I needed to create 8 text shadows, but it actually works pretty well and I was really stubborn on using vtt cues for compatibility reasons with other platforms and devices over a custom display
> 
> regions don't work, and aren't supported in some browsers ex: chrome, but are in firefox, its a shitstorm 😓

Awesome creative approach with such limited tools! 😄 

I was trying to do this mkv embedded subtitles thing years ago, but the specs for adding text dynamically kept changing and never really worked great. I think vtt cues might have evolved from that, but back then it seemed like it had become completely abandoned for static tracks. It's great to see that this is actually possible even though support still kinda sucks :D

**Comment by ThaUnknown** [comment]
> > yup. at least most of it, that includes linebreaks etc etc, vtt lacks a LOT of shit, so for example for a 2px outline around the text I needed to create 8 text shadows, but it actually works pretty well and I was really stubborn on using vtt cues for compatibility reasons with other platforms and devices over a custom display
> > regions don't work, and aren't supported in some browsers ex: chrome, but are in firefox, its a shitstorm 😓
> 
> Awesome creative approach with such limited tools! 😄
> 
> I was trying to do this mkv embedded subtitles thing years ago, but the specs for adding text dynamically kept changing and never really worked great. I think vtt cues might have evolved from that, but back then it seemed like it had become completely abandoned for static tracks. It's great to see that this is actually possible even though support still kinda sucks :D

I'm surprised mkv still hasn't died out in favor of shit like webm, but I guess it must have its advantages, and even more surprised that after all these years its support is still so shit, this entire webtorrent browser server thing is because you can't really stream mkv in html5 player, 80% of all work in this website of mine has been .mkv support, it's crazy

**Comment by mathiasvr** [comment]
> I'm surprised mkv still hasn't died out in favor of shit like webm, but I guess it must have its advantages, and even more surprised that after all these years its support is still so shit, this entire webtorrent browser server thing is because you can't really stream mkv in html5 player, 80% of all work in this website of mine has been .mkv support, it's crazy

webm is actually a subset of mkv - that's how good it is 😆 
Why can't you stream mkv in html5 player though? And how can webtorrent browser server do it?

**Comment by mathiasvr** [comment]
> seems like most of my issues were caused by either preload or autoplay, they do some REALLY weird shit where some fragments of the video and metadata aren't requested at all, that's what was causing my initial cue issues, not using those breaks some of my other modules, but I'm okay with parting ways with them for this to work

Do you have some code snippet of this preload/autoplay stuff?

**Comment by ThaUnknown** [comment]
> > seems like most of my issues were caused by either preload or autoplay, they do some REALLY weird shit where some fragments of the video and metadata aren't requested at all, that's what was causing my initial cue issues, not using those breaks some of my other modules, but I'm okay with parting ways with them for this to work
> 
> Do you have some code snippet of this preload/autoplay stuff?

just add a preload and/or auto play property to the video element, that's it, no longer on pc

**Comment by ThaUnknown** [comment]
> > I'm surprised mkv still hasn't died out in favor of shit like webm, but I guess it must have its advantages, and even more surprised that after all these years its support is still so shit, this entire webtorrent browser server thing is because you can't really stream mkv in html5 player, 80% of all work in this website of mine has been .mkv support, it's crazy
> 
> webm is actually a subset of mkv - that's how good it is 😆
> Why can't you stream mkv in html5 player though? And how can webtorrent browser server do it?

because yes

the lib we torrent used doesn't support mkv and forcing HTML to play it just errored out, idk it's weird shit

**Comment by mathiasvr** [comment]
> because yes
> 
> the lib we torrent used doesn't support mkv and forcing HTML to play it just errored out, idk it's weird shit

Yeah, it's a mess. A common problem with mkv is that because it can contain any audio/video codec, it's easily a codec that is not supported by chrome, etc. while webm only uses supported codecs (that's kinda the whole idea).

**Comment by mathiasvr** [comment]
Okay so apparently the mkv seek head can reference other seek heads which is what I think was often range requested, this didn't happen in my smaller files.
For what we care they can be used like cues, so I updated to add all of them to the list.
This way autoplay works for me now.

There's still the caching problem though.

One solution is to parse metadata (header, seeks, cues), before using the player ranges.
This will require implementing some stream control, and not just intercepting what the player is doing.
However, if we control the stream we might as well parse the subtitles based on timestamps rather than "random" range offsets, this is what the cues are for in the first place.

Sorry I'm just taking notes and thinking out load here :p

Anyway, I'll try to see if I can parse the metadata later. 
Please let me know if you find another way to avoid caching, or have other issues - still needs more testing!

**Comment by ThaUnknown** [comment]
> Okay so apparently the mkv seek head can reference other seek heads which is what I think was often range requested, this didn't happen in my smaller files.
> For what we care they can be used like cues, so I updated to add all of them to the list.
> This way autoplay works for me now.
> 
> There's still the caching problem though.
> 
> One solution is to parse metadata (header, seeks, cues), before using the player ranges.
> This will require implementing some stream control, and not just intercepting what the player is doing.
> However, if we control the stream we might as well parse the subtitles based on timestamps rather than "random" range offsets, this is what the cues are for in the first place.
> 
> Sorry I'm just taking notes and thinking out load here :p
> 
> Anyway, I'll try to see if I can parse the metadata later.
> Please let me know if you find another way to avoid caching, or have other issues - still needs more testing!

it hasn't solved the autoplay/manual play issue for me, this is what the requests look like with autoplay:
![image](https://user-images.githubusercontent.com/6506529/93201028-e33b9a80-f750-11ea-8c8a-60e0e1e431ef.png)

and without:
![image](https://user-images.githubusercontent.com/6506529/93200966-cdc67080-f750-11ea-9bce-56dc2eac572c.png)

this is weird, the old parser didn't have issues with autoplay at all when I created a separate filestream starting from byte 0 so how come it worked?


 one idea I had is that the video element gets created/requests data before metadata is downloaded, so chrome fallbacks to cache? if this is true then this is most likely a webtorrent issue and would need some sort of fix on webtorrent's part, ~~iirc there's some onmetadata events for file downloading~~ [there's one for the torrent but not single files]

**Comment by ThaUnknown** [comment]
got really annoyed with the caching, so said "fuck it" and pasted in everything I could find that prevents store and caching, most of it is most likely not needed and some of it might not even work, ~~but testing this properly takes sooo long~~ did it anyways, seems like all of these are needed, which doesn't make sense since no-store already implies no-cache, and there wouldn't be anything to re-validate, and you can't set the age of 0 of something that isn't stored, but oh well... chrome shenanigans
```js
    res.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate, max-age=0'
    res.headers['Expires'] = '0'
```
seems to have solved the issue tho \o/

but for playback, if you seek to an undownloaded area, then seek back to a downloaded one you'll need to wait for it to download the first part, so it isn't flawless ;-;

**Comment by mathiasvr** [comment]
> it hasn't solved the autoplay/manual play issue for me, this is what the requests look like with autoplay:
> ![image](https://user-images.githubusercontent.com/6506529/93201028-e33b9a80-f750-11ea-8c8a-60e0e1e431ef.png)

This looks okay, it does not need the cues unless you seek, so as long as it actually begins parsing subtitles it's fine.
From the log I can't see if you seeked or came across a point that should output subtitles though.

> this is weird, the old parser didn't have issues with autoplay at all when I created a separate filestream starting from byte 0 so how come it worked?

With old parser do you mean the one currently on npm? If starting from 0 it should work mostly the same now.

**Comment by ThaUnknown** [comment]
> This looks okay, it does not need the cues unless you seek, so as long as it actually begins parsing subtitles it's fine.
From the log I can't see if you seeked or came across a point that should output subtitles though.

it never parses subtitles, don't know why, it finds tracks etc, but doesn't parse subtitles until I seek at least once

**Comment by ThaUnknown** [comment]
torrent i used ```1b0250c4bc532e28e6b2d88934f3cd6b00174806``` dont expect many seeders tho

**Comment by mathiasvr** [comment]
> ```js
>     res.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate, max-age=0'
>     res.headers['Expires'] = '0'
> ```
> 
> seems to have solved the issue tho \o/

Doesn't work for me 😢 but have only tried the usual stuff, maybe chrome has it in some of its infinite cache layers somewhere.

**Comment by mathiasvr** [comment]
> 1b0250c4bc532e28e6b2d88934f3cd6b00174806

Worked the first time, but not after reload. AHH and I forgot to log it. So many traps in this mkv business.

**Comment by ThaUnknown** [comment]
> > ```js
> >     res.headers['Cache-Control'] = 'no-cache, no-store, must-revalidate, max-age=0'
> >     res.headers['Expires'] = '0'
> > ```
> > 
> > 
> > seems to have solved the issue tho \o/
> 
> Doesn't work for me 😢 but have only tried the usual stuff, maybe chrome has it in some of its infinite cache layers somewhere.

yeah, realized that too, it sometimes works, not always, once out of 10 times it will cache something and fuck it up, no clue why it happens like that xD

>Worked the first time, but not after reload. AHH and I forgot to log it. So many traps in this mkv business.

looked like that was the case, and I really hoped it was, I hope it's an easy fix ^^

**Comment by mathiasvr** [comment]
Still looks like a cache problem to me, it's like certain parts of the video are still cached even if you get it to start from 0. It keeps skipping over the first subtitle tracks.

**Comment by ThaUnknown** [comment]
> Still looks like a cache problem to me, it's like certain parts of the video are still cached even if you get it to start from 0. It keeps skipping over the first subtitle tracks.

100% isn't because it happens even after I fully clear cache and with caching disabled in networking

**Comment by mathiasvr** [comment]
> > Still looks like a cache problem to me, it's like certain parts of the video are still cached even if you get it to start from 0. It keeps skipping over the first subtitle tracks.
> 
> 100% isn't because it happens even after I fully clear cache and with caching disabled in networking

Actually yes me too, I have to dig deeper.

**Comment by mathiasvr** [comment]
Okay, so this file didn't have a seek head which meant it needed the cues after all.
The problem is that when it makes a range request for an offset around the beginning we lose all information about how to decode the file, because the mkv/ebml decoder used is so sensitive.
I think this can be fixed by adding a seek point around the last place we left off when creating a new instance.
But will it cover all cases, probably not. Maybe the better solution is to make the decoder more robust, but I don't really feel like it.

Will try the seek point thing though...

**Comment by mathiasvr** [comment]
I updated the branch with the "previous instance seek point" patch, seems to fix autoplay... again lol.
It's great to have you testing it, finding all these bugs early really helps a lot.

**Comment by ThaUnknown** [comment]
> I updated the branch with the "previous instance seek point" patch, seems to fix autoplay... again lol.
> It's great to have you testing it, finding all these bugs early really helps a lot.

hahah, yw, it's not like I'm totally doing it for my own sake XD

**Comment by ThaUnknown** [comment]
hmmmm.... after a few seconds it breaks, there's quite a bit of logging spam so I'll show as much as I can
![image](https://user-images.githubusercontent.com/6506529/93267083-625dbc80-f7ab-11ea-9120-ee5a087a7b8d.png)
this is caused solely by autoplay, because it requests bigger pieces at once than if you didin't use it [in chrome ~x2 as big as without it], however the issue with attempting to play the video early is fixed, preloading is all sorts of fucked, but I think chrome is to blame on that, this bigger pieces issue could however be an issue in some situations with custom players?

**Comment by ThaUnknown** [comment]
this library has such a tiny use case its crazy, it's only really useful for custom players and streaming data, but if you're doing that you probably have a backend, and this shit could be done x100 easier and quicker on the backend, but I love it XD

**Comment by mathiasvr** [comment]
> hmmmm.... after a few seconds it breaks, there's quite a bit of logging spam so I'll show as much as I can

Right I added a bit of logging 😆 
What do you mean breaks? Is it just the high skip warning or does it stop working?
Looks like range request with high skip ends quite quickly and another takes over. It's only really "bad" if your stuck with it.
Btw high skip basically means that no subtitle parsing will take place for a long time (if ever).

> this library has such a tiny use case its crazy, it's only really useful for custom players and streaming data, but if you're doing that you probably have a backend, and this shit could be done x100 easier and quicker on the backend, but I love it XD

Well, it's really just a subtitle parser, which could be used on a backend to extract subtitles and serve them in a way that players actually support.
But yes the shit we are working on now is basically insane - trying to parse it in the last second and most indirect way possible, cause why not.
Not to mention that doing this on the frontend would be even easier. It would just be a tiny piece of ebml parsing (which is already implemented) of the subtitle tracks in the chrome video player. But I don't think it will happen because they don't care about mkv or embedded subtitles.

**Comment by ThaUnknown** [comment]
> > hmmmm.... after a few seconds it breaks, there's quite a bit of logging spam so I'll show as much as I can
> 
> Right I added a bit of logging 😆
> What do you mean breaks? Is it just the high skip warning or does it stop working?
> Looks like range request with high skip ends quite quickly and another takes over. It's only really "bad" if your stuck with it.
> Btw high skip basically means that no subtitle parsing will take place for a long time (if ever).
> 
> > this library has such a tiny use case its crazy, it's only really useful for custom players and streaming data, but if you're doing that you probably have a backend, and this shit could be done x100 easier and quicker on the backend, but I love it XD
> 
> Well, it's really just a subtitle parser, which could be used on a backend to extract subtitles and serve them in a way that players actually support.
> But yes the shit we are working on now is basically insane - trying to parse it in the last second and most indirect way possible, cause why not.
> Not to mention that doing this on the frontend would be even easier. It would just be a tiny piece of ebml parsing (which is already implemented) of the subtitle tracks in the chrome video player. But I don't think it will happen because they don't care about mkv or embedded subtitles.

it straight up stops parsing subtitles, playback works tho

well I'm using this to do it on the frontend, but yeah if chromium implemented it themselves it would be miles easier, maybe you could do that, tho it's a bit late for mkv 😂 idk if chromium is open source or not, never really looked at it hahahaha

**Comment by mathiasvr** [comment]
> it straight up stops parsing subtitles, playback works tho

Really, why can you always break it so easily 😭 

> well I'm using this to do it on the frontend, but yeah if chromium implemented it themselves it would be miles easier, maybe you could do that 😂 idk if chromium is open source or not, never really looked at it hahahaha

Yes it's open source but I don't think they would accept stuff like this.

**Comment by ThaUnknown** [comment]
> Really, why can you always break it so easily 😭

I was born with a talent to fuck shit up, it's actually a curse

**Comment by mathiasvr** [comment]
> I was born with a talent to fuck shit up, it's actually a curse

lol, I tried but I don't have your talent, could you share the file? Or copy-paste the full log.

**Comment by ThaUnknown** [comment]
> > I was born with a talent to fuck shit up, it's actually a curse
> 
> lol, I tried but I don't have your talent, could you share the file? Or copy-paste the full log.

same one as before but you're gonna need to add some trackers manually, imma paste the log after some more testing since I don't want to lose torrent download progress

**Comment by ThaUnknown** [comment]
can't reproduce it, it's possible I fucked something when playing with preloading and it cached? oops....
EDIT: it's a caching issue, turn on caching in network tools and it happens, but I'm not sure why it happens on the first load.....
and chrome straight up shits itself when trying to save the log

TLDR this isn't an issue with the parser but more of chrome shenanigans, bad testing on my part sorry

**Comment by mathiasvr** [comment]
> can't reproduce it, it's possible I fucked something when playing with preloading and it cached? oops....
> EDIT: it's a caching issue, turn on caching in network tools and it happens, but I'm not sure why it happens on the first load.....
> and chrome straight up shits itself when trying to save the log

Nice though I completely forgot to test with cache, but currently I'm having some loading problems.

**Comment by ThaUnknown** [comment]
shit seems fine, watched 2 separate movies with 2 different subtitle types and shit, seeking buffering etc, it all seemed to work fine, I'll let this issue stay open for a few days in case I run into further issues, but damn from what I can tell this works outstandingly well, it loads subtitles way before the initial frame is even rendered, after that, it's probably safe to clean up and merge this in

**Comment by ThaUnknown** [comment]
> > can't reproduce it, it's possible I fucked something when playing with preloading and it cached? oops....
> > EDIT: it's a caching issue, turn on caching in network tools and it happens, but I'm not sure why it happens on the first load.....
> > and chrome straight up shits itself when trying to save the log
> 
> Nice though I completely forgot to test with cache, but currently I'm having some loading problems.

elaborate? the caching workaround I sent actually doesn't work instantly, if you re-play the video too quickly it's still cached, but refreshing the website twice instead of once without any devtools enabled doesn't load the video from cache, tho I loaded it quite a bit after the refresh and you load it as soon as DOM is ready IIRC so maybe try putting the client.add in a timeout or function to run manually at will

**Comment by mathiasvr** [comment]
> elaborate? the caching workaround I sent actually doesn't work instantly, if you re-play the video too quickly it's still cached, but refreshing the website twice instead of once without any devtools enabled doesn't load the video from cache, tho I loaded it quite a bit after the refresh and you load it as soon as DOM is ready IIRC so maybe try putting the client.add in a timeout or function to run manually at will

I finally made it happen haha.

**Comment by ThaUnknown** [comment]
> > elaborate? the caching workaround I sent actually doesn't work instantly, if you re-play the video too quickly it's still cached, but refreshing the website twice instead of once without any devtools enabled doesn't load the video from cache, tho I loaded it quite a bit after the refresh and you load it as soon as DOM is ready IIRC so maybe try putting the client.add in a timeout or function to run manually at will
> 
> I finally made it happen haha.

well again, it was a caching issue, goal was to fix playing as soon as the video was ready, you fixed that so you should be good, autoplay is fixed too except for the caching part which is out of your control ¯\\\_(ツ)\_/¯

**Comment by mathiasvr** [comment]
> well again, it was a caching issue, goal was to fix playing as soon as the video was ready, you fixed that so you should be good, autoplay is fixed too except for the caching part which is out of your control ¯\_(ツ)_/¯

yes looks like your right.

**Comment by mathiasvr** [comment]
So I still have this idea to extract metadata through stream control, which should make it work even when cached.
The only problem left would be that the cached parts would not emit subtitles, but I just thought of routing the subtitles through a service worker URL so they will basically be cached as well 😄 
I feel like I'm on to something here, please don't tell anyone about how useless this is in practice 🤣

**Comment by ThaUnknown** [comment]
> So I still have this idea to extract metadata through stream control, which should make it work even when cached.
> The only problem left would be that the cached parts would not emit subtitles, but I just thought of routing the subtitles through a service worker URL so they will basically be cached as well 😄
> I feel like I'm on to something here, please don't tell anyone about how useless this is in practice 🤣

now you're just having fun :p

disabling caching is good enough because webtorrent will always re-download data anyways so it's not like it matters :p

**Comment by mathiasvr** [comment]
> now you're just having fun :p
> 
> disabling caching is good enough because webtorrent will always re-download data anyways so it's not like it matters :p

Maybe you're right, but can you reliably disable caching? I tried `client.add` with a timeout, but still caching...

**Comment by mathiasvr** [comment]
Somewhat unrelated but I have this small ssa/ass "key extraction" in the code that seems like it doesn't really belong there.
I haven't really used those formats much, but since you're quite the expert I was just wondering if it's actually useful or should I just remove it?

So basically this is the subtitle output with it:
```js
{
  text: 'In ancient, mythical times,',
  layer: '0',
  style: 'italics',
  name: 'Na',
  marginL: '0',
  marginR: '0',
  marginV: '0',
  effect: '',

  time: 6280,
  duration: 1990
}
```

and without:
```js
{
  text: '0,0,italics,Na,0,0,0,,In ancient, mythical times,',

  time: 6280,
  duration: 1990
}
```
The key order is hardcoded but it looks like the .ass header defines it, maybe this ordering is just very common idk.
Thoughts?

**Comment by ThaUnknown** [comment]
> Somewhat unrelated but I have this small ssa/ass "key extraction" in the code that seems like it doesn't really belong there.
> I haven't really used those formats much, but since you're quite the expert I was just wondering if it's actually useful or should I just remove it?
> 
> So basically this is the subtitle output with it:
> 
> ```js
> {
>   text: 'In ancient, mythical times,',
>   layer: '0',
>   style: 'italics',
>   name: 'Na',
>   marginL: '0',
>   marginR: '0',
>   marginV: '0',
>   effect: '',
> 
>   time: 6280,
>   duration: 1990
> }
> ```
> 
> and without:
> 
> ```js
> {
>   text: '0,0,italics,Na,0,0,0,,In ancient, mythical times,',
> 
>   time: 6280,
>   duration: 1990
> }
> ```
> 
> The key order is hardcoded but it looks like the .ass header defines it, maybe this ordering is just very common idk.
> Thoughts?

honestly, I'd keep it as it is, IF vtt API actually worked like it was designed to this would be super useful since one wouldnt need to make their own parser for it.... which... isn't fun... but if some1 is making some sort of custom subtitle display/renderer it could be useful, but maybe an option not to format it would be good for people that just want to plug in some existing library for it?

also it's use heavily relies on the subber too, some people use tags, some people use the style tag in the cue itself, so it's best to support all

also I'm in no way an expert, this is barely my 2nd month coding shit XD

**Comment by ThaUnknown** [comment]
> > now you're just having fun :p
> > disabling caching is good enough because webtorrent will always re-download data anyways so it's not like it matters :p
> 
> Maybe you're right, but can you reliably disable caching? I tried `client.add` with a timeout, but still caching...

I meaaaan... that's on the end user not you if they can't tbh, what I do works, sure it has a few patches here and there, but it works \o/

**Comment by mathiasvr** [comment]
> honestly, I'd keep it as it is, IF vtt API actually worked like it was designed to this would be super useful since one wouldnt need to make their own parser for it.... which... isn't fun... but if some1 is making some sort of custom subtitle display/renderer it could be useful, but maybe an option not to format it would be good for people that just want to plug in some existing library for it?

I'll keep it. Even though what you wrote after that kinda felt like it should be removed 😆 

> also it's use heavily relies on the subber too, some people use tags, some people use the style tag in the cue itself, so it's best to support all

This makes me worry that it will extract something wrong but if it's not a problem for you I guess it's fine.

> also I'm in no way an expert, this is barely my 2nd month coding shit XD

Sorry but you are an .ass expert now! 😅

**Comment by mathiasvr** [comment]
> I meaaaan... that's on the end user not you if they can't tbh, what I do works, sure it has a few patches here and there, but it works \o/

yea idk, but the cache though?! THE CACHE?! You gotta fight it from all sides 😉 

I would love to see your project btw, is it something you can share?

**Comment by ThaUnknown** [comment]
> > I meaaaan... that's on the end user not you if they can't tbh, what I do works, sure it has a few patches here and there, but it works \o/
> 
> yea idk, but the cache though?! THE CACHE?! You gotta fight it from all sides 😉
> 
> I would love to see your project btw, is it something you can share?

discord me ThaUnknown_#5291

**Comment by ThaUnknown** [comment]
guessing you dont have discord then @mathiasvr :P

**Comment by ThaUnknown** [comment]
further testing[aka me watching shit for a few hours :D]: randomaccess works really well, tho the sample size was small since WS seeders are few and far between, but I think it's safe to clean up debug and somehow this into master, gonna close this and create a new issue in the future if I run into trouble
